language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction --dev

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
